---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    # when: ansible_distribution == "Ubuntu"
    when: ansible_distribution in ["Ubuntu", "CentOS"]


  - name: install apache2 package
    apt: 
      name: apache2
      state: latest

  - name: add php and htop support for apache
    apt:
      name: 
        - libapache2-mod-php
        - htop
        - vim
      state: latest